# Generated by Django 5.2.16 on 2026-08-08 20:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='content_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='target_role',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.CharField(blank=True, default='modern', max_length=100),
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('commit_message', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('snapshot_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='resumes.resume')),
            ],
            options={
                'verbose_name': 'resume version',
                'verbose_name_plural': 'resume versions',
                'db_table': 'resume_version',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resume', '-created_at'], name='resume_ver_created_idx')],
            },
        ),
    ]
