# Generated by Django 5.2.16 on 2026-08-13 04:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_resume_content_data_resume_job_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField(default=0)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='resumes.resume')),
            ],
            options={
                'verbose_name': 'resume analysis',
                'verbose_name_plural': 'resume analyses',
                'db_table': 'resume_analysis',
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['resume', '-analyzed_at'], name='resume_an_analyzed_idx')],
            },
        ),
    ]
