# Generated by Django 5.2.16 on 2026-08-07 16:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round', models.CharField(blank=True, default='Round 1', max_length=100)),
                ('interview_type', models.CharField(choices=[('screening', 'Screening Call'), ('technical', 'Technical Interview'), ('behavioral', 'Behavioral Interview'), ('system_design', 'System Design'), ('hr', 'HR / Culture Fit'), ('final', 'Final Round')], default='technical', max_length=32)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=32)),
                ('location_or_link', models.CharField(blank=True, default='', max_length=500)),
                ('interviewer_name', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application')),
            ],
            options={
                'verbose_name': 'interview',
                'verbose_name_plural': 'interviews',
                'db_table': 'interview',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
