# Generated by Django 5.2.16 on 2026-08-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='ai_prep_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='interview',
            name='prep_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='interview',
            name='reflection',
            field=models.TextField(blank=True, default=''),
        ),
    ]
