# Generated by Django 5.2.16 on 2026-07-30 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career_profile', '0002_add_audit_timestamps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careerprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'career profile', 'verbose_name_plural': 'career profiles'},
        ),
    ]
