# Generated by Django 5.2.16 on 2026-08-14 11:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_coach', '0001_initial'),
        ('career_profile', '0005_education_career_profile'),
        ('jobs', '0003_skillgapanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRoadmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('target_role', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='in_progress', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmaps', to='career_profile.careerprofile')),
                ('target_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmaps', to='jobs.savedjob')),
            ],
            options={
                'verbose_name': 'career roadmap',
                'verbose_name_plural': 'career roadmaps',
                'db_table': 'career_roadmap',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapPhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('objective', models.TextField(blank=True, default='')),
                ('skills', models.JSONField(blank=True, default=list)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='upcoming', max_length=32)),
                ('ordering', models.PositiveIntegerField(default=1)),
                ('estimated_duration', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='ai_coach.careerroadmap')),
            ],
            options={
                'verbose_name': 'roadmap phase',
                'verbose_name_plural': 'roadmap phases',
                'db_table': 'roadmap_phase',
                'ordering': ['ordering', 'created_at'],
            },
        ),
    ]
