# Generated by Django 5.2.16 on 2026-08-07 16:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('career_profile', '0005_education_career_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('salary_range', models.CharField(blank=True, default='', max_length=100)),
                ('source', models.CharField(blank=True, default='', max_length=100)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('applied', 'Applied'), ('archived', 'Archived')], default='saved', max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='career_profile.careerprofile')),
            ],
            options={
                'verbose_name': 'saved job',
                'verbose_name_plural': 'saved jobs',
                'db_table': 'saved_job',
                'ordering': ['-saved_at'],
            },
        ),
    ]
