# Generated by Django 5.2.16 on 2026-08-14 10:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_profile', '0005_education_career_profile'),
        ('jobs', '0002_jobmatchanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillGapAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matched_skills', models.JSONField(blank=True, default=list)),
                ('missing_skills', models.JSONField(blank=True, default=list)),
                ('partial_skills', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('career_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gap_analyses', to='career_profile.careerprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gap_analyses', to='jobs.savedjob')),
            ],
            options={
                'verbose_name': 'skill gap analysis',
                'verbose_name_plural': 'skill gap analyses',
                'db_table': 'skill_gap_analysis',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
